name: testes
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2
  equatable: 1.2.5
  get: 3.4.2
  provider:
  flutter_secure_storage: 3.3.5
  localstorage: 3.0.6+9
  carousel_slider: 2.3.1
  intl: 0.16.1

dev_dependencies:
  flutter_launcher_icons: 0.8.1
  flutter_test:
    sdk: flutter
  test: 1.15.0
  mockito: 3.0.2
  faker: 1.3.0
  image_test_utils: 1.0.0

flutter:
  uses-material-design: true 
  assets:
    - lib/ui/assets/  
    
flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assetsicon/background.png
  adaptive_icon_foreground: lib/ui/assetsicon/foreground.png